import type { Metadata } from "next";
import '@/app/globals.css';
import Nav from '@/app/components/nav';
import Get from '@/app/components/get';
import games from '@/app/images/WhatsApp Image 2024-12-04 at 9.41.42 PM.jpeg';
import Image from "next/image";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
      
       
  
     <main>{children}</main>

      </body>
     
    </html>
  );
}
